version: "2"
services:
  goof:
    build: .
    container_name: goof
    environment:
      - DOCKER=1
    ports:
      - "3001:3001"
      - "9229:9229"
    depends_on:
      - goof-mongo
      - goof-mysql
    links:
      - goof-mongo
      - goof-mysql

  goof-mongo:
    image: arm64v8/mongo:4.4
    container_name: goof-mongo
    ports:
      - "27017:27017"

  goof-mysql:
    image: arm64v8/mysql:5.7
    container_name: goof-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acme
    ports:
      - "3306:3306"
